title: Steven Gilandas
#logo: /assets/img/headshot_circle.png
# relative path in github repo
description: **Profile:** I am a Data Analyst with an interest in Biostatistics.  Fulfilling work for me is approaching a problem in a creative way and building solutions that are technically robust.  I treat my technical output as a teaching opportunity - a way to engage with people and build knowledge.   Iâ€™m particularly interested in using population health data to solve systemic problems in the way healthcare is delivered to communities.
# show_downloads: true
# download zip/ tar/ go to github
# download the code
theme: jekyll-theme-minimal
